{{- if .Values.ollama.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ollama
    {{- include "openwebui-dremio.labels" . | nindent 4 }}
  name: {{ .Values.ollama.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: ollama
  ports:
  - protocol: TCP
    port: {{ .Values.ollama.service.port }}
    targetPort: {{ .Values.ollama.service.port }}
  type: {{ .Values.ollama.service.type }}
{{- end }}

---

{{- if .Values.mcpo.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mcpo
    {{- include "openwebui-dremio.labels" . | nindent 4 }}
  name: {{ .Values.mcpo.service.name }}
  namespace: {{ .Values.namespace }}
  {{- if .Values.mcpo.service.annotations }}
  annotations:
    {{- toYaml .Values.mcpo.service.annotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: mcpo
  ports:
  - protocol: TCP
    port: {{ .Values.mcpo.service.port }}
    targetPort: {{ .Values.mcpo.service.port }}
  type: {{ .Values.mcpo.service.type }}
{{- end }}

---

{{- if .Values.openwebui.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openwebui
    {{- include "openwebui-dremio.labels" . | nindent 4 }}
  name: {{ .Values.openwebui.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: openwebui
  ports:
  - protocol: TCP
    port: {{ .Values.openwebui.service.port }}
    targetPort: {{ .Values.openwebui.service.targetPort }}
  type: {{ .Values.openwebui.service.type }}
{{- end }}

